name: attendance_system_flutter_mobile
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.0.2
  provider: ^6.0.4
  firebase_core: ^2.1.0
  cloud_firestore: ^4.0.2
  convex_bottom_bar: ^3.0.0
  introduction_screen: ^2.1.0
  shared_preferences: ^2.0.13
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.1.6
  http: ^0.13.5
  firebase_database: ^10.0.4
  firebase_storage: ^11.0.4
  ndialog: ^4.2.0
  intl: ^0.17.0
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  fluttertoast: ^8.1.1
  encrypt: ^5.0.1
  rive: ^0.9.1
  badges: ^2.0.3
  flutter_inset_box_shadow: ^1.0.8
  date_picker_timeline: ^1.2.3
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.2
  transparent_image: ^2.0.0
  awesome_notifications: ^0.6.21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf

